#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v4
# autospec commit: f4bef72
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : analitza
Version  : 24.02.1
Release  : 76
URL      : https://download.kde.org/stable/release-service/24.02.1/src/analitza-24.02.1.tar.xz
Source0  : https://download.kde.org/stable/release-service/24.02.1/src/analitza-24.02.1.tar.xz
Source1  : https://download.kde.org/stable/release-service/24.02.1/src/analitza-24.02.1.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause CC0-1.0 GFDL-1.2 GPL-2.0 LGPL-2.0
Requires: analitza-data = %{version}-%{release}
Requires: analitza-lib = %{version}-%{release}
Requires: analitza-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : eigen-data
BuildRequires : eigen-dev
BuildRequires : extra-cmake-modules-data
BuildRequires : glew-dev
BuildRequires : qtbase-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package data
Summary: data components for the analitza package.
Group: Data

%description data
data components for the analitza package.


%package dev
Summary: dev components for the analitza package.
Group: Development
Requires: analitza-lib = %{version}-%{release}
Requires: analitza-data = %{version}-%{release}
Provides: analitza-devel = %{version}-%{release}
Requires: analitza = %{version}-%{release}

%description dev
dev components for the analitza package.


%package lib
Summary: lib components for the analitza package.
Group: Libraries
Requires: analitza-data = %{version}-%{release}
Requires: analitza-license = %{version}-%{release}

%description lib
lib components for the analitza package.


%package license
Summary: license components for the analitza package.
Group: Default

%description license
license components for the analitza package.


%prep
%setup -q -n analitza-24.02.1
cd %{_builddir}/analitza-24.02.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711064876
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1711064876
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/analitza
cp %{_builddir}/analitza-%{version}/COPYING %{buildroot}/usr/share/package-licenses/analitza/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/analitza-%{version}/COPYING.DOC %{buildroot}/usr/share/package-licenses/analitza/1bd373e4851a93027ba70064bd7dbdc6827147e1 || :
cp %{_builddir}/analitza-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/analitza/ba8966e2473a9969bdcab3dc82274c817cfd98a1 || :
cp %{_builddir}/analitza-%{version}/LICENSES/BSD-2-Clause.txt %{buildroot}/usr/share/package-licenses/analitza/07c1ab270255cf247438e2358ff0c18835b6a6ce || :
cp %{_builddir}/analitza-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/analitza/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/analitza-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/analitza/3cb34cfc72e87654683f2894299adf912d14b284 || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/qt6/qml/org/kde/analitza/Graph2D.qml
/usr/lib64/qt6/qml/org/kde/analitza/Graph3D.qml
/usr/lib64/qt6/qml/org/kde/analitza/analitzadeclarativeplugin.qmltypes
/usr/lib64/qt6/qml/org/kde/analitza/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/analitza/qmldir

%files data
%defattr(-,root,root,-)
/usr/share/libanalitza/plots/3Ds.plots
/usr/share/libanalitza/plots/basic_curves.plots
/usr/share/libanalitza/plots/conics.plots
/usr/share/libanalitza/plots/polar.plots
/usr/share/locale/ar/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/ast/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/bs/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/ca/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/ca@valencia/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/cs/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/da/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/de/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/el/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/en_GB/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/eo/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/es/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/et/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/eu/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/fi/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/fr/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/ga/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/gl/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/hu/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/ia/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/it/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/ja/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/ka/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/kk/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/ko/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/lt/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/lv/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/ml/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/mr/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/nb/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/nds/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/nl/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/nn/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/pl/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/pt/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/pt_BR/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/ru/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/se/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/sk/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/sl/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/sv/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/tr/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/ug/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/uk/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/zh_CN/LC_MESSAGES/analitza_qt.qm
/usr/share/locale/zh_TW/LC_MESSAGES/analitza_qt.qm

%files dev
%defattr(-,root,root,-)
/usr/include/Analitza6/analitza/abstractexpressionvisitor.h
/usr/include/Analitza6/analitza/abstractlexer.h
/usr/include/Analitza6/analitza/analitzaexport.h
/usr/include/Analitza6/analitza/analitzautils.h
/usr/include/Analitza6/analitza/analyzer.h
/usr/include/Analitza6/analitza/apply.h
/usr/include/Analitza6/analitza/builtinmethods.h
/usr/include/Analitza6/analitza/container.h
/usr/include/Analitza6/analitza/customobject.h
/usr/include/Analitza6/analitza/expression.h
/usr/include/Analitza6/analitza/expressionstream.h
/usr/include/Analitza6/analitza/expressiontype.h
/usr/include/Analitza6/analitza/importqobjectmetatype.h
/usr/include/Analitza6/analitza/list.h
/usr/include/Analitza6/analitza/matrix.h
/usr/include/Analitza6/analitza/object.h
/usr/include/Analitza6/analitza/operations.h
/usr/include/Analitza6/analitza/operator.h
/usr/include/Analitza6/analitza/value.h
/usr/include/Analitza6/analitza/variable.h
/usr/include/Analitza6/analitza/variables.h
/usr/include/Analitza6/analitza/vector.h
/usr/include/Analitza6/analitza_version.h
/usr/include/Analitza6/analitzagui/algebrahighlighter.h
/usr/include/Analitza6/analitzagui/analitzaguiexport.h
/usr/include/Analitza6/analitzagui/analitzawidgets_export.h
/usr/include/Analitza6/analitzagui/expressionedit.h
/usr/include/Analitza6/analitzagui/operatorsmodel.h
/usr/include/Analitza6/analitzagui/plotsview2d.h
/usr/include/Analitza6/analitzagui/plotsview3d_es.h
/usr/include/Analitza6/analitzagui/variablesmodel.h
/usr/include/Analitza6/analitzaplot/analitzaplotexport.h
/usr/include/Analitza6/analitzaplot/functiongraph.h
/usr/include/Analitza6/analitzaplot/planecurve.h
/usr/include/Analitza6/analitzaplot/plotitem.h
/usr/include/Analitza6/analitzaplot/plotsdictionarymodel.h
/usr/include/Analitza6/analitzaplot/plotsfactory.h
/usr/include/Analitza6/analitzaplot/plotsmodel.h
/usr/include/Analitza6/analitzaplot/plotter2d.h
/usr/include/Analitza6/analitzaplot/plotter3d_es.h
/usr/include/Analitza6/analitzaplot/plottingenums.h
/usr/include/Analitza6/analitzaplot/spacecurve.h
/usr/include/Analitza6/analitzaplot/surface.h
/usr/lib64/cmake/Analitza6/Analitza6Config.cmake
/usr/lib64/cmake/Analitza6/Analitza6ConfigVersion.cmake
/usr/lib64/cmake/Analitza6/Analitza6Targets-relwithdebinfo.cmake
/usr/lib64/cmake/Analitza6/Analitza6Targets.cmake
/usr/lib64/libAnalitza.so
/usr/lib64/libAnalitzaGui.so
/usr/lib64/libAnalitzaPlot.so
/usr/lib64/libAnalitzaWidgets.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libAnalitza.so.8.0.0
/V3/usr/lib64/libAnalitzaGui.so.8.0.0
/V3/usr/lib64/libAnalitzaPlot.so.8.0.0
/V3/usr/lib64/libAnalitzaWidgets.so.8.0.0
/V3/usr/lib64/qt6/qml/org/kde/analitza/libanalitzadeclarativeplugin.so
/usr/lib64/libAnalitza.so.8
/usr/lib64/libAnalitza.so.8.0.0
/usr/lib64/libAnalitzaGui.so.8
/usr/lib64/libAnalitzaGui.so.8.0.0
/usr/lib64/libAnalitzaPlot.so.8
/usr/lib64/libAnalitzaPlot.so.8.0.0
/usr/lib64/libAnalitzaWidgets.so.8
/usr/lib64/libAnalitzaWidgets.so.8.0.0
/usr/lib64/qt6/qml/org/kde/analitza/libanalitzadeclarativeplugin.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/analitza/07c1ab270255cf247438e2358ff0c18835b6a6ce
/usr/share/package-licenses/analitza/1bd373e4851a93027ba70064bd7dbdc6827147e1
/usr/share/package-licenses/analitza/3cb34cfc72e87654683f2894299adf912d14b284
/usr/share/package-licenses/analitza/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/analitza/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/analitza/ba8966e2473a9969bdcab3dc82274c817cfd98a1
